hello_the_world:
    path:     /hello-world
    defaults: { _controller: AccueilFirstBundle:Advert:index }

bye_the_world:
    path:     /byebye-world
    defaults: { _controller: AccueilFirstBundle:Advert:bye }

oc_platform_view:
    path:      /platform/advert/{id}
    defaults:  { _controller: AccueilFirstBundle:Advert:view }

oc_platform_view_slug:
    path: /platform/{year}/{slug}.{_format}
    defaults: { _controller: AccueilFirstBundle:Advert:viewSlug, format: html}
    requirements:
        year:   \d{4}
        format: html|xml
